### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by luvnft** [mihairusu88/nextjs-booking#1]
Great work. Do you have any information on how to add services and details to the app?

**Comment by mihairusu88** [comment]
Hey, there is no automatic mechanism developed so far, so if you want to add services and details you have to do it inside supabase database from their admin panel. I hope this helps :)

![Screenshot 2024-05-24 at 17 36 39](https://github.com/mihairusu88/nextjs-booking/assets/45873011/c18e10bf-6b62-4068-9d4f-65806771732c)
